
server:
  port: 8080
  servlet:
    context-path: /feige-im
spring:
  application:
    name: feige-im
    admin:
      enabled: true
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password:
    url: jdbc:mysql://localhost:3306/im
    druid:
      stat-view-servlet:
        enabled: true
        login-password: admin
        login-username: admin
  redis:
    database: 0
    host: localhost
    port: 6379
    password: 123456
    redisson:
      config: classpath:redisson-dev.yml
  rabbitmq:
    template:
      exchange: feige.im
    requested-heartbeat: 0

nacos:
  discovery:
    enabled: true
    server-addr: 127.0.0.1:8848
    namespace: public
spring.http.encoding.force: true
spring.http.encoding.charset: UTF-8
spring.http.encoding.enabled: true
server.tomcat.uri-encoding: UTF-8
#RabbitMQ Properties
spring.rabbitmq.host: 127.0.0.1
spring.rabbitmq.port: 5672
spring.rabbitmq.username: guest
spring.rabbitmq.password: guest
spring.rabbitmq.virtual-host: /
spring.rabbitmq.publisher-returns: true
spring.rabbitmq.connection-timeout: 30000
mybatis-plus:
  global-config:
    db-config:
      #逻辑删除配置
      logic-delete-field: deleted
      logic-delete-value: 1
      logic-not-delete-value: 0
  configuration:
    log-impl: org.apache.ibatis.logging.slf4j.Slf4jImpl
logging:
  level:
    com.ds.feige.im: debug
oss:
  domain: "http://35.220.161.103:8080"
  group: group1
  token-secret: OAaLBf1Ho87nDxGd
  token-expire-seconds: 3600
  #500M
  max-file-size: 524288000
user:
  security:
    tokenSignSecret: AayLgXaWNoWS
