server.port: 8080
server.servlet.context-path: /feige-im
spring.application.name: feige-im
spring.application.admin.enabled: true
spring.http.encoding.force: true
spring.http.encoding.charset: UTF-8
spring.http.encoding.enabled: true
server.tomcat.uri-encoding: UTF-8
#数据库配置
spring.datasource.driver-class-name: com.mysql.jdbc.Driver
spring.datasource.username: root
#spring.datasource.password: oim_root
#spring.datasource.url: jdbc:mysql://35.220.161.103:3306/oim
spring.datasource.url: jdbc:mysql://127.0.0.1:3306/im
#spring.datasource.password: oim_root
spring.datasource.password:
#druid配置
spring.datasource.druid.stat-view-servlet.enabled: true
spring.datasource.druid.stat-view-servlet.login-password: admin
spring.datasource.druid.stat-view-servlet.login-username: admin
#redis配置
spring.redis.database: 0
spring.redis.host: localhost
spring.redis.port: 6379
spring.redis.password: 123456
spring.redis.redisson.config: classpath:redisson-dev.yml
#RabbitMQ配置
spring.rabbitmq.template.exchange: feige.im
spring.rabbitmq.requested-heartbeat: 0
spring.rabbitmq.listener.simple.acknowledge-mode: auto
spring.rabbitmq.listener.simple.retry.enabled: true
spring.rabbitmq.listener.simple.retry.max-attempts: 3
spring.rabbitmq.listener.simple.retry.initial-interval: 2000
#  设置为false，会丢弃消息或者重新发布到死信队列
spring.rabbitmq.listener.simple.default-requeue-rejected: false
spring.rabbitmq.template.mandatory: true
spring.rabbitmq.host: 127.0.0.1
spring.rabbitmq.port: 5672
spring.rabbitmq.username: guest
spring.rabbitmq.password: guest
spring.rabbitmq.virtual-host: /
spring.rabbitmq.publisher-returns: true
spring.rabbitmq.connection-timeout: 30000
#nacos配置
nacos.discovery.enabled: true
nacos.discovery.server-addr: 127.0.0.1:8848
nacos.discovery.namespace: public
#mybatis配置
mybatis-plus.global-config.db-config.logic-delete-field: deleted
mybatis-plus.global-config.db-config.logic-delete-value: 1
mybatis-plus.global-config.db-config.logic-not-delete-value: 0
mybatis-plus.configuration.log-impl: org.apache.ibatis.logging.slf4j.Slf4jImpl
logging.level.com.ds.feige.im: debug
##业务相关
oss.domain: http://35.220.161.103:8080
oss.group: group1
oss.token-secret: OAaLBf1Ho87nDxGd
oss.token-expire-seconds: 3600
oss.max-file-size: 524288000
user.security.tokenSignSecret: AayLgXaWNoWS
##推送相关
push.mode: dev
push.google-credentials: credentials/firebase-credentials.json